<template>
  <div>
    <!-- Head metadata -->
    <head>
      <title>Cinema App</title>
      <meta name="description" content="Generated by Vue.js" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </head>

    <!-- Navbar Component -->
    <NavBar />

    <!-- Main Grid Layout -->
    <div class="grid" style="height: 100%;">
      <div class="grid-item">
        <MovieHeading />
        <MovieGrid />
      </div>

      <div class="grid-item" style="text-align: center;">
        <!-- Display Pagination if more than one page -->
        <Pagination v-if="nbPages > 1" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { useMoviesStore } from '../stores/moviesStore' // Pinia store
import NavBar from '../components/Navbar/NavBar'
import MovieGrid from '@/components/MovieGrid'
import MovieHeading from '@/components/MovieHeading'
import Pagination from '@/components/Pagination'

export default defineComponent({
  components: {
    NavBar,
    MovieGrid,
    MovieHeading,
    Pagination,
  },
  setup() {
    const moviesStore = useMoviesStore()
    const { nbPages } = moviesStore

    return {
      nbPages,
    }
  },
})
</script>

<style scoped>
.grid {
  display: grid;
  grid-template-rows: auto 1fr 2fr; /* Define three rows: navbar, main grid, pagination */
  grid-template-columns: 1fr;
  gap: 1rem;
}

.grid-item {
  /* Custom styles for grid items if necessary */
}
</style>
